### ISSUE TITLE
Cannot save after changing name

### ISSUE THREAD

**Issue by lonnie776** [Alorel/melvor-action-workflows#144]
### Platform

Steam

### Category

Other/Not sure

### Bug description

After the recent update, I tried to modify an existing workflow but I changed almost all of it. So I renamed it but I was unable to save it after that. I would click save and nothing would happen. It stays on the edit workflow screen.

After I changed the name back to what it originally was, I was able to save the changes.

### Steps to reproduce

1. Edit Workflow
2. Change Name
3. Attempt to save

### Code of Conduct

- [X] I agree to follow the code of conduct
- [X] I have searched for similar issues and nothing similar exists

**Comment by Alorel** [comment]
There's more to it, but I have no idea what - I got the same bug _once_ but was unable to reproduce it afterwards nor inspect any of the data because it was on a non-debug build :/ In my case changing the name back didn't fix it and I just lost my workflow changes. 

Validation seems to be out of sync between the UI and the actual data; the only things that cause the button to intentionally not do anything are

1. An empty or duplicate workflow name
1. Data validation errors in some step

and clicking "save" should™ force them both to start showing error messages, but inspecting the workflow config manually didn't reveal anything invalid..

I'll keep an eye out, but no ETA on the fix. Might need to add the workflow export button to the edit page as a failsafe so people can at least export and re-import the workflow as JSON without losing anything.
