### ISSUE TITLE
Add ability to import/export workflows

### ISSUE THREAD

**Issue by Alorel** [Alorel/melvor-action-workflows#42]
And probably add a note on the weird format, how it's meant to compress the data for Melvor's 8 kB limit etc.

Should just be a Swal modal with a `<textarea>`

**Comment by kellewic** [comment]
Already hitting the 8kb limit with a single workflow so having export/import would be great. 

I actually can't finish the workflow due to the limit, which is just a mine essence to X amount then create X amount of runes with jump back to beginning. I do make use of And/Or triggers to check rune amount OR out of essence - I assume that trigger takes up more space.

Some sort of templatized step might help with the limit since essentially every step in this sort of workflow is the same.

**Comment by Alorel** [comment]
I was gonna say that's one hell of a workflow, but then I only have 3 relatively tiny ones that that's already 2147 bytes when in storage

<details>
<summary>JSON</summary>

```json
[{"name":"Fire God Dungeon","rm":false,"steps":[["actions","trigger"],[[[["opts","id","action"],[[{"set":1},null,"ActionWorkflows:equipSet"],[{},null,"ActionWorkflows:activatePrayers"]]],{"opts":{"mob":"melvorF:FireGuard"},"id":"ActionWorkflows:mobID","action":null}],[[["opts","id","action"],[[{"set":2},null,"ActionWorkflows:equipSet"]]],{"opts":{"mob":"melvorF:FireGolem"},"id":"ActionWorkflows:mobID","action":null}],[[["opts","id","action"],[[{"prayers":["melvorF:Rigour"]},null,"ActionWorkflows:activatePrayers"]]],{"opts":{"mob":"melvorF:Pyra"},"id":"ActionWorkflows:mobID","action":null}],[[["opts","id","action"],[[{"set":1},null,"ActionWorkflows:equipSet"],[{"prayers":["melvorF:Augury"]},null,"ActionWorkflows:activatePrayers"]]],{"opts":{"mob":"melvorF:Ignis"},"id":"ActionWorkflows:mobID","action":null}],[[["opts","id","action"],[[{"set":2},null,"ActionWorkflows:equipSet"],[{"prayers":["melvorF:Rigour","melvorF:Sharp_Vision"]},null,"ActionWorkflows:activatePrayers"]]],{"opts":{"mob":"melvorF:Ragnar"},"id":"ActionWorkflows:mobID","action":null}]]]},{"name":"Rokken","rm":false,"steps":[["actions","trigger"],[[[["opts","id","action"],[[{"prayers":["melvorF:Protect_from_Ranged","melvorF:Piety"]},null,"ActionWorkflows:activatePrayers"]]],{"opts":{"match":"=","atk":"melvorF:ShockwaveEnemy"},"id":"ActionWorkflows:enemyAtk","action":null}],[[["opts","id","action"],[[{"prayers":["melvorF:Piety"]},null,"ActionWorkflows:activatePrayers"],[{"idx":0},null,"ActionWorkflows:setStepIdx"]]],{"opts":{"match":"!=","atk":"melvorF:ShockwaveEnemy"},"id":"ActionWorkflows:enemyAtk","action":null}]]]},{"name":"Umbora","rm":false,"steps":[["actions","trigger"],[[[["opts","id","action"],[[{"prayers":["melvorF:Augury","melvorF:Protect_from_Melee"]},null,"ActionWorkflows:activatePrayers"]]],{"opts":{"match":"=","atk":"melvorF:RapidOnslaught"},"id":"ActionWorkflows:enemyAtk","action":null}],[[["opts","id","action"],[[{"prayers":["melvorF:Augury"]},null,"ActionWorkflows:activatePrayers"],[{"idx":0},null,"ActionWorkflows:setStepIdx"]]],{"opts":{"match":"!=","atk":"melvorF:RapidOnslaught"},"id":"ActionWorkflows:enemyAtk","action":null}]]]}]
```

</details>

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/4998038/206753434-a93bd7d0-d53c-4fb0-9119-cccb6a4acc90.png)
![image](https://user-images.githubusercontent.com/4998038/206753450-45f28d09-cac9-40b6-8483-bba41eab214f.png)
![image](https://user-images.githubusercontent.com/4998038/206753480-416a300f-aea2-4052-a34e-3decce8e7699.png)


</details>

I'll have a look at this on Sunday - gonna be travelling over the weekend so won't have time in the next couple of days. I think this bumps #43 up the priority list as well - if _this_ is how easy it is to hit Melvor's limit then I think having mods define entire workflows might end up being the way to go - the fire god dungeon workflow, for example, then  wouldn't take up nearly as much space and would only need a few inputs like which equipment sets to use. If we're still consistently hitting size limits afterwards then I might need to think about storing workflows somewhere outside `mod.io`.

Using mod namespaces for action/trigger IDs felt nice and convenient too (allows me to reuse a bunch of the game's code for mod logic), but ends up with quite a bit of space wastage too..

**Comment by kellewic** [comment]
For reference, here's a screenshot of the workflow. I can't add the "and/or" to the first set of runes due to size. The and/or is "if rune qty >= 1000000 OR essence qty <= 0" - that way it doesn't get stuck if I run out of essences and the last step jumps back to mining essences. All steps past the first three would essentially be the same, just different parameters.
<details><summary>Screenshot</summary><p>
![wkflow](https://user-images.githubusercontent.com/3178267/206762707-bc7df3ee-efb6-42cf-80cd-fbc967e4eff0.jpg)
</p></details>
